### PR TITLE
v3.0 - improve readIniFile()

### PR DESCRIPTION
**Pull request by earthlng**
- grep -c equals grep | wc -l
- make output prettier
- work with variable instead of temporary file

### CODE REVIEW

**Comment by earthlng** [comment]
This was part of an older [pull request](https://github.com/arkenfox/user.js/pull/1000) by @h88e22dgpeps56sg that we didn't finish back then.

Now was a good time to revisit that because we may want to reuse it (or do something similar) in the prefsCleaner.sh.

I already tested it under Linux but would like to get some feedback, improvements or more testing done (especially for Mac) by someone else before I commit it.
@overdodactyl, @ema-pe, @claustromaniac, @h88e22dgpeps56sg or anyone else - thanks!

**Comment by ema-pe** [comment]
Hi, in the next days I can give some feedback. What happened to `ghacks-user.js`?

**Comment by rusty-snake** [comment]
> What happened to ghacks-user.js?

Was renamed, #1014 and #1009.

**Comment by h88e22dgpeps56sg** [comment]
Looks good to me. :) Just 2 things:
1.) line 127: `if [ $(grep -c '^\[Profile' "${inifile}") == "1" ]`
I'd rather use `if [ $(grep -c '^\[Profile' "${inifile}") -eq "1" ]`. grep outputs an int and -eq compares ints. `==` is a pattern matching which works but is equally as fast at best but probably slower.
2.) line 133: `echo;`
Replacing this with another line of `echo -e "––––––––––––––––––––––––––––––"` might look nice.

**Comment by earthlng** [comment]
Hey, thanks for your feedback!

> Looks good to me. :)

I'd hope so :)

> grep outputs an int

good to know, thanks. Done

re: line 133 - yeah looks nice

I'll commit it now but more feedback, improvements, etc is still welcome.

**Pull request merged**
