### PR TITLE
5506: Only link to CVE with firefox

### PR DESCRIPTION
**Pull request by rusty-snake**

### CODE REVIEW

**Comment by rusty-snake** [comment]
Target branch is https://github.com/arkenfox/user.js/pull/1527.

**Comment by Thorin-Oakenpants** [comment]
I prefer to keep it as is, rather than just show 3 Firefox CVEs. The existing link and 36 CVEs with six from this year, back up the item

>  * Vulnerabilities [1] have increasingly been found

**Comment by rusty-snake** [comment]
Yes, but why link to CVEs oft other wasm runtimes which share no code with Firefox AFAIK.

**Comment by Thorin-Oakenpants** [comment]
because the description is talking about wasm in general, not wasm in Firefox

**Pull request closed without merging**
