### PR TITLE
v106

### PR DESCRIPTION
**Pull request by Thorin-Oakenpants**
cleanout pre-102 info

### CODE REVIEW

**Comment by opusforlife2** [comment]
Is this blocked on something? No hurries, it's just that I would like to test WebRTC after the huge version jump.

**Comment by rusty-snake** [comment]
What has WebRTC to do with this?

**Comment by opusforlife2** [comment]
The version jump occurred in 106.

**Comment by rusty-snake** [comment]
IDK what you're talking about. And IDK what this PR has do to with it.

**Comment by opusforlife2** [comment]
I'm a noob. I don't upgrade to the new version until the corresponding AF version is released, in case there are any privacy-related changes I've missed.

**Comment by fxbrit** [comment]
he's talking about a library update (libwebrtc) that was part of v106, but it has no overlap with arkenfox. don't wait for the corresponding AF version, update your firefox as soon as an update is available.

**Comment by opusforlife2** [comment]
> don't wait for the corresponding AF version, update your firefox as soon as an update is available.

Isn't that exactly what led to the mess with 102 and 103?

**Comment by fxbrit** [comment]
IDK what you're referring to and this is not the right place anyway, but the changes between releases are very minimal these days. so users should always update Firefox ASAP, and the user.js later when available.

**Comment by Thorin-Oakenpants** [comment]
> Is this blocked on something?

I'm having my hair and nails done. Chill.

**Pull request merged**
