### PR TITLE
proxy direct failover

### PR DESCRIPTION
**Pull request by Thorin-Oakenpants**
https://hg.mozilla.org/integration/autoland/rev/b633563955ad

### CODE REVIEW

**Comment by Thorin-Oakenpants** [comment]
needs more cowbell.. feel free to edit and merge

**Comment by Thorin-Oakenpants** [comment]
bump

**Comment by Thorin-Oakenpants** [comment]
@Jee-Hex @rusty-snake .. looks like earthlng has gone again, trying to save the world from trumpism .. is 0706 correct? please advise .. I've got my 91 changelog post ready to go .. its a doozey!

**Comment by rusty-snake** [comment]
I do not understood it to 100% yet (and the bugzilla and phabricator links require log-in :disappointed: ) but from what I understood so far (FF91+):
- `network.proxy.failover_direct=true` (default) if there is a broken proxy config firefox fails back to direct connections if 1. there is no other working proxy-config and 2, the proxy wasn't configured manually by the user.
- `network.proxy.failover_direct=false` firefox never skips a proxy. A broken proxy config will always break.

==> Setting `network.proxy.failover_direct=false` sounds right.

Points that I did not understood so far:
- What are system principal requests?
- Blocked bugzillas are usually about security, can this affect security?

**Comment by Thorin-Oakenpants** [comment]
[system principal](https://blog.mozilla.org/attack-and-defense/2020/06/10/understanding-web-security-checks-in-firefox-part-1/)

Yeah, false is what we want, so nothing bypasses your proxy settings. I have no idea if the bugzilla is directly security related, if it was then it the default value would be false IMO. I just thought the description needs to be better. I copied the line from the patch to get something up for E to edit and push .. but he vanished again. Proxies and networking is not my area. Guess we'll wait :)

**Comment by rusty-snake** [comment]
> system principal

Thanks.

>  just thought the description needs to be better.

So based on what I understood so far: `disable direct connections for privileged origins on misconfiguration proxys` (or maybe use chrome instead of privileged)

**Comment by Thorin-Oakenpants** [comment]
> disable direct connections for privileged origins on misconfiguration proxys

Not very user friendly, and neither is mine

**Comment by Jee-Hex** [comment]
>  I have no idea if the bugzilla is directly security related, if it was then it the default value would be false IMO. 

Apparently this pref was introduced to "combat malicious add-ons".

> the description 


Maybe something like `Prevent system requests from failing over outside the proxy` or
`Prevent system principal requests from falling back to DIRECT connections`, give or take?

**Comment by earthlng** [comment]
> Apparently this pref was introduced to "combat malicious add-ons".

where did you find that?

Sure would be nice if the bugzilla wasn't hidden from the public and we could see the discussion and reasoning for this new pref,
and fe. the likely scenario that they think this needs to protect against.
I don't really see how falling back to Direct combats malicious addons if fe. an addon sets a proxy to spy on their users.
It does more of the opposite, doesn't it? Like when the intercepting proxy isn't reachable for whatever reason, users are less likely to notice that a malicious addon is intercepting them when Firefox just switches over to a direct connection, no?
The only other "malicious" use I can imagine, is an addon configuring a nonexistant proxy address to block all internet access but that doesn't really make sense either because it's kinda stupid, easily noticeable and can also be done with the "requests" API.
So yeah, IDK.

IMO, just "disable proxy failover to DIRECT", or something like that, is good enough. No need to mention "system requests". IDK if it needs an additional description either.

**Comment by Thorin-Oakenpants** [comment]
> IMO, just "disable proxy failover to DIRECT", or something like that, is good enough. No need to mention "system requests". IDK if it needs an additional description either.

The system principal seems like a very important variable here. Since your proposal isn't really any different to mine (except the "system" bit), then I'll leave it as is. We can always update it later

> Apparently this pref was introduced to "combat malicious add-ons"

I'm confused. I thought web ext wasn't system principal, but expanded principal

**Comment by Jee-Hex** [comment]
> where did you find that?

[here](https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/40548)

> I don't really see how falling back to Direct combats malicious addons if fe. an addon sets a proxy to spy on their users.

> I'm confused. I thought web ext wasn't system principal, but expanded principal

presumably they wanted to enforce the add-on blocklist?

**Comment by Thorin-Oakenpants** [comment]
> here

Ahh OK. I pinged sysrqb on it, but he never replied. Not sure how I missed that issue. And here I was thinking it might be some weird edge cases for web content like service worker blobs or something

**Comment by Thorin-Oakenpants** [comment]
I know more now, got an email from @tomrittervg (moz security dev) , not sure what I can share about it. 

From a security standpoint for Firefox, we want the pref to be true (default), and yes, it protects against malicious addons interfering with legit FF system principal proxy requests

For Tor Browser, I get the proxy leak aspect

So we should make this inactive and stick it under harden with a more info: at the end of the day, people need to vet their extensions, so I'm not terrible torn up about it - class discuss

**Pull request merged**
