### PR TITLE
Fix default value of browser.contentanalysis.default_allow

### PR DESCRIPTION
**Pull request by rusty-snake**

### CODE REVIEW

**Comment by Thorin-Oakenpants** [comment]
did they rename it to `default_result`?

https://searchfox.org/mozilla-central/search?q=contentanalysis.default&path=&case=false&regexp=false

**Comment by rusty-snake** [comment]
Uhh, yes. It's not the same pref.

https://bugzilla.mozilla.org/show_bug.cgi?id=1880314
https://hg.mozilla.org/integration/autoland/rev/7b85c82d731d

**Comment by Thorin-Oakenpants** [comment]
I just did some checkin' yeah

user_pref("browser.contentanalysis.enabled", false); // [FF121+] [DEFAULT: false]
user_pref("browser.contentanalysis.default_allow", false); // [FF124+] [DEFAULT: false]

so default_allow is now gone (or hidden) and default_result is new in FF127

**Comment by Thorin-Oakenpants** [comment]
I'll stick all this in v127

**Pull request closed without merging**
