### PR TITLE
updater.sh: cope if run with sudo [withdrawn see #1651 instead]

### PR DESCRIPTION
**Pull request by icpantsparti2**
hi @earthlng, some small additions that 'might' help with [#1587](https://github.com/arkenfox/user.js/issues/1587). Thank you.

in version 3.5 if you run updater.sh with sudo then: (1) user.js may only be readable by root and not load for the Firefox user (2) if the script is run first time with sudo, then again without sudo, permissions from the previous run may cause issues (eg no backup or update of user.js) with little or no warning.

Therefore v3.6 to: (1) set some file/dir permissions (on those created) if run with sudo (2) show info if some access permissions are not as expected (3) added some further error messages

### CODE REVIEW

**Comment by CelestialNebula** [comment]
(I don't know how macOS works they may do different stuff for root.)

https://stackoverflow.com/questions/18215973/how-to-check-if-running-as-root-in-a-bash-script
I can't see any reason to use sudo, so I think this is simpler (added at
the start):
```
if [ "${EUID:-$(id -u)}" -eq 0 ]
then
	printf "You shouldn't run this as root.\n"
	exit 1
fi
```

I doubt it will matter but this may catch more https://stackoverflow.com/a/65358284:
```
ls /root > /dev/null 2>&1 && { printf "You shouldn't run this as root.\n"
			       exit 1; }
```

**Comment by mhmdanas** [comment]
@CelestialNebula's suggestion makes sense, you should definitely not run a command or script with `sudo` unless it's absolutely necessary. I would be especially careful with running `sudo` for anything downloaded from the internet.

@CelestialNebula I have macOS and wouldn't mind testing anything if needed.

**Comment by CelestialNebula** [comment]
@mhmdanas 
I heard that macos switched to zsh and it seems that supports EUID [1] and it does more or less the same thing.

If you could test this to confirm:

test.sh:
```
#!/usr/bin/env sh

if [ "${EUID:-$(id -u)}" -eq 0 ]
then
	printf "You shouldn't run this as root.\n"
	exit 1
fi
```
`$ sudo sh test.sh`

If it worked you should see: You shouldn't run this as root.
Then run
`$ echo $?`
and it should be 1

[1] https://zsh.sourceforge.io/Doc/Release/Parameters.html#Parameters-Set-By-The-Shell

**Comment by mhmdanas** [comment]
@CelestialNebula apologies for the delay. I tested the script you provided with macOS's Dash, Bash, and Zsh, and it worked just fine under all of them.

>  Look for a line with something like root:*:0:root

There is no line in my /etc/groups file that begins with `root`.

**Comment by mhmdanas** [comment]
Sorry for the delay, I totally forgot about your comment. I followed your steps with both Dash, Bash, and Zsh, and it worked with all of them. Note that the output was this with all shells:
```
It looks like this script was previously run with elevated privileges,
you will need to change ownership of the following files to your user:
.//zfakefile
```

**Comment by icpantsparti2** [comment]
Withdrawn in favor of [#1651](https://github.com/arkenfox/user.js/pull/1651).  Closing without further action.

**Pull request closed without merging**
