### PR TITLE
v99

### PR DESCRIPTION
**Pull request by fxbrit**
#1418

### CODE REVIEW

**Comment by Thorin-Oakenpants** [comment]
am done with diffs, I didn't see anything there of any concern

one last thing I would like to do is look at `2620` `pdfjs.disabled` since RFP now reports it pdfjs as enabled (which is the default and which we enforce). I should check the browser behavior with an actual pdf (the pref directly affects the navigator property) - and depending on the results, add something to the effect that RFP enforces pdfjs as enabled

Not keen on moving it to `[SECTION 8000]: DON'T BOTHER: FINGERPRINTING` because those who don't use RFP may get the wrong message (it is perfectly fine to override as true it if you are not using RFP, in favor of some other pdf viewer - we set a good default and it's on the end user, not us)

**Comment by Thorin-Oakenpants** [comment]
um, the pdfjs thing is not a blocker, it doesn't take affect until FF100

**Comment by fxbrit** [comment]
yup, looks good considering that the only thing that stood out to me was the offscreen canvas stuff. merging.

**Comment by szepeviktor** [comment]
@Thorin-Oakenpants Why have you put back `security.csp.enable` after removing it?
Thanks.

**Comment by Thorin-Oakenpants** [comment]
I didn't remove it, fxbrit did. For deprecated items we **_move_** them to section 9999 (which is commented out), so I had to fixup the 🐟 's boo boo

**Comment by fxbrit** [comment]
https://github.com/arkenfox/user.js/pull/1419#issuecomment-1093796489 maybe turn that into an issue as a reminder?

**Comment by Thorin-Oakenpants** [comment]
^ IDK how to test this properly because handlers is a bit of a labyrinth to me
- e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1747343 just landed in 101
- and there have been some other pdf bugs as well that I've seen resolved/fixed (I check new bugzillas daily)
- and each OS may behave differently
- what test do we use, just a simple pdf to view? an inline one? IDK

So IDK if RFP affects actual handling, but it at least reports back to websites that pdfs are enabled and doesn't shouldn't you install adobe pdf viewer or whatever

**Comment by fxbrit** [comment]
it seems kinda broken honestly, I will open a new issue to report a little test of mine.

**Pull request merged**
