### PR TITLE
Simple maintenance improvements

### PR DESCRIPTION
**Pull request by a1346054**

### CODE REVIEW

**Review by rusty-snake — APPROVED** [review]

**Comment by earthlng** [comment]
Looks good to me. Thanks!

**Comment by Xathros1** [comment]
I got after running prefsCleaner the message
grep: Invalid regular expression

#1255 Typo in prefsCleaner.sh?
Line 51, bracket set incorrectly?

Change
		`done <<< "$(grep -E \"$prefexp\" user.js)"`
To
		`done <<< "($grep -E \"$prefexp\" user.js)"`

Fixed this.

**Comment by a1346054** [comment]
I'll look into this.

**Comment by a1346054** [comment]
I have the fix for this ready, am just investigating why the current version works here too and not for you.

**Comment by a1346054** [comment]
@Xathros1 #1258 will fix that issue for you, if you wish to apply it yourself.

**Comment by Xathros1** [comment]
> @Xathros1 #1258 will fix that issue for you, if you wish to apply it yourself.

Fixed it for me, Thanks!

**Pull request merged**
